<a href="https://colab.research.google.com/github/Sonuthahreen/00.-PyTorch-Fundamentals-DAY_3-/blob/main/00_PyTorch_Fundamentals(DAY3).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Reshaping, stacking, squeezing and unsqueezing**

* Reshaping - reshapes an input tensor to a defined shape


* view -return a view of an input tensor of certain shape but keep the same memory as the ORIGINAL TENSOR


* Stacking - combines multiple tensors on type of each other (Vstack) or side by side (hstack)

* unsequeeze - add a 1 dimension to a target tensor

* squeez - remove all 1 dimension from a tensor

* permute-Return a view of the input with dimensions permuted(swapped) in a certain way

In [5]:
#creating tensor
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


In [6]:
x=torch.arange(1., 10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [7]:
#to add an extra dimension
x_reshaped=x.reshape(1,9)
x_reshaped,x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [8]:
#to add an extra dimension
x_reshaped=x.reshape(9,1)
x_reshaped,x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [9]:
x=torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
#to add an extra dimension
x_reshaped=x.reshape(1,9)
x_reshaped,x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [10]:
#changing view
z=x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
#change in z changes x because a view of a tensor share the same memory as the original input

In [13]:
z[:,0]=5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [14]:
#stack tensors on top of each other
x_stacked=torch.stack([x,x,x,x],dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [24]:
#torch.squeeze()-remove all single dimensions from a targettensor
print(f"previous tensor: {x_reshaped}")
print(f"previous shape: {x_reshaped.shape}")

#remove extra dimensions from x_reshaped
x_squeezed=x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")



previous tensor: tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
previous shape: torch.Size([9, 1])

New tensor: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [28]:
#torch.unsqueeze()-adds a single dimension to a target tensor at a specific dim
print(f"previous target: {x_reshaped}")
print(f"previous shape: {x_reshaped.shape}")

#add an extra dimension with unsqueeze
x_unsqueezed=x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")


previous target: tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
previous shape: torch.Size([9, 1])

New tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [30]:
#torch.permute-rearranges the dimensions of a target tensor in a specific order
x_original=torch.rand(size=(224,224,3)) #[height,width,colour_channels]

#permute the original tennsor to rearrange the axis(or dim) order

x_permuted =x_original.permute(2,0,1) #shifts axs 0->1, 1->2, 2->0

print(f"previous shape:{x_original.shape}")
print(f"New shape:{x_permuted.shape}") #{colour_channel,height,width}


previous shape:torch.Size([224, 224, 3])
New shape:torch.Size([3, 224, 224])


In [31]:
x_original

tensor([[[0.7805, 0.5233, 0.2270],
         [0.8994, 0.2292, 0.5204],
         [0.9010, 0.6712, 0.4608],
         ...,
         [0.2532, 0.1173, 0.4176],
         [0.0681, 0.3867, 0.5987],
         [0.7654, 0.4730, 0.3414]],

        [[0.2547, 0.5573, 0.2359],
         [0.3135, 0.8388, 0.8201],
         [0.2065, 0.0767, 0.1664],
         ...,
         [0.7795, 0.0509, 0.3751],
         [0.6139, 0.7473, 0.0585],
         [0.9245, 0.1797, 0.4276]],

        [[0.3549, 0.6426, 0.8794],
         [0.2561, 0.2560, 0.8015],
         [0.1835, 0.8882, 0.8296],
         ...,
         [0.9651, 0.6674, 0.5720],
         [0.5093, 0.6396, 0.1515],
         [0.1732, 0.5174, 0.1205]],

        ...,

        [[0.5937, 0.6028, 0.5312],
         [0.5566, 0.8981, 0.2856],
         [0.9037, 0.7584, 0.9745],
         ...,
         [0.7978, 0.0718, 0.5892],
         [0.7217, 0.4359, 0.9189],
         [0.9807, 0.9099, 0.2241]],

        [[0.3336, 0.0683, 0.2672],
         [0.3884, 0.5511, 0.0164],
         [0.

In [ ]:
x=torch.zeros(2,1,2,1,2)
x.size()
torch.size([2,1,2,1,2])
y=torch.squeeze(x)
y.size()
y=torch.squeezzze(x,0)
y.size()
torch.size([2,1,2,1,2])
y=torch.squeezzze(x,1)
y.size()
torch.size([2,1,2,1,2])


In [17]:
x_reshaped

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [18]:
x_reshaped.shape

torch.Size([9, 1])

In [20]:
x_reshaped.squeeze()

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [21]:
x_reshaped.squeeze().shape

torch.Size([9])

**Indexing (selecting data from tensors)**

indexing with PyTorch is similarr to indexing with Numpy

In [34]:
#create a  tensor
import torch
x=torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [35]:
#lets index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [36]:
#index on the middle bracket(dim=1)
x[0][0]

tensor([1, 2, 3])

In [37]:
#index on the most inner bracket(last dimension)
x[0][0][0]

tensor(1)

In [40]:
x[0][1][0]

tensor(4)

In [42]:
#we can use also use":"to select "all" of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [43]:
#getting all values of )th and 1st dimensions but only index 1 0f 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [44]:
#getting all values of the 0 dimensionn but only the 1 index value of 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [45]:
#get index 0 of 0th and let dimension and all values of 2nd dimension
x[0,0,:]


tensor([1, 2, 3])

##Pytorch tensors & numpy
Numpy is a popular scientific pytho numerical computing library
and because of this pytorch has functinality to interact with it

* Data in numpy want in pytorch tensor -> 'torch.from_numpy(ndarray)

* pytorch ->Numpy->torch.tensor.numpy()

In [46]:
#numpy array to tensor
import torch
import numpy as np

array=np.arange(1.0,8.0)
tensor=torch.from_numpy(array)
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [47]:
array.dtype

dtype('float64')

In [49]:
torch.arange(1.0,8.0).dtype

torch.float32

In [50]:
#change the value of array,what will this do to'tensor'?
array=array+1
array,tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [51]:
#tensor to numpy array
tensor=torch.ones(7)
numpy_tensor=tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [52]:
tensor=tensor+1
tensor,numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

**pytorch Reproducbility**(trying to take random out of random)

in short how a neural network learns:

'start with random numbers -> tensor operations-> update random numbers to try and make them better representations of data -> again ->again...............

To reduce the randomness in neural networks and Pytorch comes the concept of randoom seed . essentially what the random seed does is "flavour" the randomness


In [53]:
torch.rand(3,3)

tensor([[0.9310, 0.6547, 0.2747],
        [0.5025, 0.3120, 0.9703],
        [0.8899, 0.4305, 0.8891]])

In [54]:
import torch

#create two random tensors

random_tensor_A=torch.rand(3,4)
random_tensor_B=torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A==random_tensor_B)

tensor([[0.0881, 0.1001, 0.3204, 0.1876],
        [0.7033, 0.1125, 0.4684, 0.4684],
        [0.0758, 0.2569, 0.9174, 0.1787]])
tensor([[0.7314, 0.3167, 0.8030, 0.1123],
        [0.9314, 0.5185, 0.2199, 0.5242],
        [0.0354, 0.4977, 0.7568, 0.1217]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [55]:
#lets make some random but reproducible tensors

import torch

#set the random seed

RANDOM_SEED=42
torch.manual_seed(RANDOM_SEED)
random_tensor_c=torch.rand(3,4)
random_tensor_D=torch.rand(3,4)

print(random_tensor_c)
print(random_tensor_D)
print(random_tensor_c==random_tensor_D)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


**Running tensors ad Pytorch objects on GPU and making faster computations**



1. Getting a GPU


2. Getting PyTorch to run on the GPU


3. Putting tensors (and models) on the GPU


4. Moving tensors back to the CPU